### ISSUE TITLE
MultiGPU training fails

### ISSUE THREAD

**Issue by mbocus** [molmod/psiflow#52]
When using more than one GPU to train a model, the calculation seems to fail when the patience is reached (around epoch 160) and a new train is readily started on the same task. The error message of the calculation is attached, any idea of what could be going wrong?

Hereafter the relevant section of my script:

```
    fn_model = path_output / 'initial_model'
    if fn_model.exists():
        model = load_model(fn_model)
    else:
        fn_model.mkdir()
        model = MACE(
            r_max=6.5,
            max_L=2,
            num_channels=16,
            energy_weight=200,
            batch_size=16,
            lr=0.005,
            num_radial_basis=10,
            patience=10,
            max_num_epochs=200, # needed for multi-gpu training to replace max_training_time
        )

        model.add_atomic_energy('H', -13.69342004905324) 
        model.add_atomic_energy('O', -432.28051880713264) 
        model.add_atomic_energy('Al', -53.149911193312) 
        model.add_atomic_energy('Si', -102.66598056598866) 

        train, valid = data.split(0.9, shuffle=True)
        model.initialize(train)
        model.train(train, valid)
        model.save(fn_model)
```

Thanks,
Massimo
[task_0125_train.txt](https://github.com/user-attachments/files/17922358/task_0125_train.txt)

**Comment by svandenhaute** [comment]
This is actually a bug in the train loop within MACE. It see it has been fixed in the most recent version of MACE at https://github.com/acesuit/mace but is apparently still present in the version pinned by psiflow.

As a workaround, you can "trick" MACE into thinking you'll use SWA but only enable it at `max_num_epochs` such that in practice it's still not used. I.e, try and instantiate your model as follows:

```py
        model = MACE(
            r_max=6.5,
            max_L=2,
            num_channels=16,
            energy_weight=200,
            batch_size=16,
            lr=0.005,
            num_radial_basis=10,
            patience=10,
            max_num_epochs=200,
            swa=True,
            start_swa=200,  # same as max_num_epochs
        )
```

But for the record; SWA reduces overfitting and improves generalization considerably so I'd strongly recommend to use it anyway.

**Comment by mbocus** [comment]
Got it, thanks a lot for the tip!
