### ISSUE TITLE
Parsl version pin: is it needed?

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [molmod/psiflow#8]
Hello, psiflow team! Thank you so much for the beautiful documentation on this package. I very much look forward to using this code in the future.

As for my question, I noticed that `parsl` is pinned to 2023.08.28 in `pyproject.toml`. Is this version pin necessary, or is it possible to relax this constraint?

**Comment by svandenhaute** [comment]
It's not needed! However, Parsl requires that manager and worker execute precisely the same version of the code. Because it has a weekly release cycle, it has happened quite often that when I set up the submission side and Apptainer container image at separate times, they install different versions of Parsl and become incompatible.  Pinning the Parsl ensures that people don't really have to worry about that anymore.

**Comment by Andrew-S-Rosen** [comment]
Ah, I see! That makes a lot of sense from a convenience standpoint. Good to know!

**Comment by Andrew-S-Rosen** [comment]
One limitation of the parsl version pin is that anyone who wants to use psiflow as a dependency can only use a specific version of Parsl, which might be limiting. Personally, I would recommend having specific version pins in a `requirements.txt` file that users would install from, which would allow for more flexibility than having them fixed in `pyproject.toml`, which should only be used for strict incompatibilities.

**Comment by svandenhaute** [comment]
Tbh, it's fair to remove the version pin. Parsl throws a clear error when there's a version mismatch, and it can easily be fixed.

**Comment by Andrew-S-Rosen** [comment]
Great, thanks!
